baseURL = 'https://keegoid.com/'
languageCode = 'en-us'
title = 'Keegoid'
enableRobotsTXT = true
enableGitInfo = true

[params]
  mainSections = ["posts"]
  description = "Sharing my routines, product recommendations, and interesting life updates."

[outputs]
  home = ["HTML"]
  page = []
  section = []
  taxonomy = []
