baseURL = 'https://keegoid.com/'
languageCode = 'en-us'
title = 'Keegoid'
enableRobotsTXT = true
enableGitInfo = true

[params]
  mainSections = ["posts"]
  description = "LLAP | Longevity hacks, gadget love, and appreciation of nature."
  defaultImage = "https://keegoid.com/images/logo.jpg"

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = true
    style = "github"
    lineNumbers = true
    defaultLang = ""

[outputs]
  home = ["HTML"]
  page = []
  section = []
  taxonomy = []
